@baseurl= http://127.0.0.1:6110
@username= test1
@password= 123
@token = 653ADF7F-FABB-4585-A9C0-8AD0E6091534


###
POST {{baseurl}}/api/user/login
content-type: application/json

{
    "username": "test1",
    "password": "123"
}

###

GET {{baseurl}}/api/user/info
token: {{token}}

###
POST  {{baseurl}}/api/user/register
content-type: application/json

{
    "username": "test1",
    "password": "123",
}

###
POST {{baseurl}}/api/user/save_money
content-type: application/json
token: {{token}}

{
    "money":1000
}

### 
POST {{baseurl}}/api/user/withdraw_money
content-type: application/json
token: {{token}}

{
    "money":1000
}

###
POST {{baseurl}}/api/user/money_deal
content-type: application/json
token: {{token}}

{
    "toUserId":"testfakeid",
    "money":100
}

###
GET {{baseurl}}/api/record/list
token: {{token}}